! CONTATO: amanda.batista@estudante.ufjf.br ===========================================
! =========amandab.dsantosg@gmail.com=================================================

PROGRAM CALCULOPOTENCIAL
IMPLICIT NONE
!============= POTENCIAL DE UM SISTEMA DIATÔMICO =============
INTEGER, PARAMETER :: dp = KIND(1.0D0) ! Define a precisão como DOUBLE PRECISION
DOUBLE PRECISION :: PRIMEIRO, ULTIMO, INTERVALO, PASSO
INTEGER :: I, io, N, PONTOS

! DOMINIO ARMAZENA AS VARIAVEIS DO DOMINIO DA FUNÇÃO V(R)
DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: R
! POTENCIAL ARMAZENA AS VARIAVEIS DA IMAGEM DA FUNÇÃO V(R)
DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: V
! QUANTOS PONTOS DO GRÁFICO SERÃO CALCULADOS
PONTOS = 100000
! VALOR DO PRIMEIRO PONTO DO DOMINIO RMIN
PRIMEIRO = 0.0D0
! VALOR DO ULTIMO PONTO DO DOMINIO RMAX
ULTIMO = 55.5D0

ALLOCATE(R(PONTOS))
ALLOCATE(V(PONTOS))
PASSO = ((ULTIMO - PRIMEIRO) / (PONTOS - 1))

! ESCREVE OS PONTOS E CALCULA O POTENCIAL EM CADA PONTO
DO I = 1, PONTOS
    R(I) = PRIMEIRO + ((I - 1) * PASSO)
    V(I) = POT(R(I))
END DO

! IMPRIME
OPEN (newunit=io, file="plot.dat", status="replace", action="write")
DO I = 1, PONTOS
    WRITE(io, *) R(I), V(I)
END DO

CONTAINS

DOUBLE PRECISION FUNCTION POT(X)
    IMPLICIT NONE
    DOUBLE PRECISION :: X, POTENCIAL
    ! COEFICIENTES DE MORSE
    DOUBLE PRECISION :: ALFA, BETA, GAMA
    ! PARÂMETROS ESPECTROSCÓPICOS
    DOUBLE PRECISION :: RE, DE
    DOUBLE PRECISION :: BE
    ! VALOR DE 1CM-1 EM HARTREE Eh
    DOUBLE PRECISION, PARAMETER :: CONVERT = 4.556335252920D-6
    ! AUXILIA O SOMATÓRIO DO POTENCIAL
    DOUBLE PRECISION :: POT_TRANS
    ! VETOR C ARMAZENA COEFICIENTES CN DE 2 A 8 NO MÁXIMO
    DOUBLE PRECISION, DIMENSION(2:6) :: C

    POTENCIAL = 0.0D0
    ! ATRIBUINDO VALORES DO Cs2 EM Eh, cmE-1 e a0E-1
    DE = 0.01663000D0
    BE = 0.01174260D0 * CONVERT
    RE = 8.78530000D0
    ALFA = 0.30370000D0
    BETA = 0.10123000D0
    GAMA = 2.00000000D0

    OPEN (newunit=io, file="coef.dat", status="old", action="read")
    READ(io, *) C(2)
    READ(io, *) C(3)
    READ(io, *) C(4)
    READ(io, *) C(5)
    READ(io, *) C(6)
    CLOSE(io)

        ! CALCULA O POTENCIAL
    IF (X <= RE) THEN
        DO N = 2, 6
            POT_TRANS = (C(N) * (((1 + EXP(-2.0D0 * BETA * ((X - RE) / RE)))**N) * ((X - RE) / X)**N))
            POTENCIAL = POTENCIAL + POT_TRANS
        END DO
    ELSE
        POTENCIAL = DE * (((1 - (EXP(-2.0D0 * ALFA * (X - RE)))) / &
            (1 + (EXP(-GAMA * ALFA * (X - RE)))))**2)
    END IF

    POT = POTENCIAL - DE
END FUNCTION POT

END PROGRAM CALCULOPOTENCIAL
